Add PR github template
danguilherme/spotivy pull request #23
Opened 2019-10-01 21:48 UTC by jmlavoier

# PR Details
Add a github PR template

### Description
It's a template that's going to guide contribuitors to create a clean and well explained pull requests

### Related Issue
https://github.com/danguilherme/spotivy/issues/16

### Types of changes
*What types of changes does your code introduce? Put an `x` in all the boxes that apply:*

- [x] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist
*Go over all the following points, and put an `x` in all the boxes that apply.*
*If you're unsure about any of these, don't hesitate to ask. We're here to help!*

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2019-10-16 23:16 UTC, 1-byte-man approved these changes

2019-10-17 07:44 UTC, danguilherme requested changes
Hey, thanks for contributing!

Sorry for the delay... Could you just take a look at the comments?

2019-10-17 07:44 UTC, danguilherme commented on .github/ISSUE_TEMPLATE.md
> +- Additional tools:
I can't think of anything that could be added as "additional tools". What did you think of? I believe we can remove it to keep things simple.

2019-10-17 07:44 UTC, danguilherme commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] All new and existing tests passed.
The repo still has no tests 😬

Maybe change it to "I have tested my changes locally" or something similar?
At least it's a manual checkbox that will (hopefully) make the contributor to test it a bit further? (Or even test it at all... happens sometimes.)

2019-10-23 14:24 UTC, danguilherme approved these changes

2019-10-23 14:25 UTC, merged